# Task 1:

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def divide_by_zero():
    return 5/0

In [2]:
try:
    divide_by_zero()
except ZeroDivisionError:
    print('Exception occurred due to division by zero!')
except Exception:
    print('Caught exception')
finally:
    print('Execute finally')

Exception occurred due to division by zero!
Execute finally


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [3]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
sentence_list = [(subject + " " + verb + " " + obj) for subject in subjects for verb in verbs for obj in objects]
for sentence in sentence_list:
    print(sentence +".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [6]:
import numpy as np
def vandermonde_matrix(input_vector,num_of_output_columns):
    return np.column_stack([input_vector**(num_of_output_columns-i-1) for i in range(num_of_output_columns)])

In [7]:
print(vandermonde_matrix(np.array([1,3,5,6]),7))

[[    1     1     1     1     1     1     1]
 [  729   243    81    27     9     3     1]
 [15625  3125   625   125    25     5     1]
 [46656  7776  1296   216    36     6     1]]
